// Database types for the public schema.
// This file is regenerated by `npm run db:types` (supabase gen types) once a
// Supabase project is linked; it is hand-maintained to match migration 0001
// until then.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      church_settings: {
        Row: {
          created_at: string
          email_from_name: string | null
          id: string
          logo_url: string | null
          name: string
          singleton: boolean
          timezone: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email_from_name?: string | null
          id?: string
          logo_url?: string | null
          name: string
          singleton?: boolean
          timezone?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email_from_name?: string | null
          id?: string
          logo_url?: string | null
          name?: string
          singleton?: boolean
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      people: {
        Row: {
          auth_user_id: string | null
          created_at: string
          email: string | null
          first_name: string
          id: string
          last_name: string
          role: Database['public']['Enums']['app_role']
          updated_at: string
        }
        Insert: {
          auth_user_id?: string | null
          created_at?: string
          email?: string | null
          first_name: string
          id?: string
          last_name: string
          role?: Database['public']['Enums']['app_role']
          updated_at?: string
        }
        Update: {
          auth_user_id?: string | null
          created_at?: string
          email?: string | null
          first_name?: string
          id?: string
          last_name?: string
          role?: Database['public']['Enums']['app_role']
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_person_role: {
        Args: Record<PropertyKey, never>
        Returns: Database['public']['Enums']['app_role']
      }
      is_admin: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
    }
    Enums: {
      app_role: 'admin' | 'leader' | 'member'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T]
